### ISSUE TITLE
python tests fail on windows

### ISSUE THREAD

**Issue by anniesullie** [google/trace-viewer#1093]
After https://codereview.appspot.com/251100043/, there are still 3 failing tests. I'm not sure how to handle c:\ getting stuck on the absolute paths in Windows. Output:

======================================================================
ERROR: testInlineStylesheetURLs (tvcm.html_module_unittest.HTMLModuleTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\html_module_unittest.py", line 359, in testInlineStylesheetURLs
    my_component.AppendDirectlyDependentFilenamesTo(computed_deps)
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\html_module.py", line 89, in AppendDirectlyDependentFilenamesTo
    self.loader, module_dirname, contents)
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\style_sheet.py", line 34, in __init__
    self._Load(containing_dirname)
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\style_sheet.py", line 88, in _Load
    self._images = [resolve_url(x) for x in matches]
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\style_sheet.py", line 84, in resolve_url
    image = self.loader.LoadImage(abs_path)
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\resource_loader.py", line 186, in LoadImage
    raise module.DepsException("url('%s') did not exist" % abs_path)
DepsException: While loading:
  a.b.my_component
Got: url('c:\tmp\a\something.jpg') did not exist

======================================================================
ERROR: testGetAllDependentFilenamesRecursive (tvcm.module_unittest.ModuleIntegrationTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\module_unittest.py", line 118, in testGetAllDependentFilenamesRecursive
    my_module = loader.LoadModule(module_name='z.foo')
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\resource_loader.py", line 140, in LoadModule
    m.Load()
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\html_module.py", line 38, in Load
    super(HTMLModule, self).Load()
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\module.py", line 187, in Load
    style_sheet = self.loader.LoadStyleSheet(name)
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\resource_loader.py", line 177, in LoadStyleSheet
    style_sheet.load()
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\style_sheet.py", line 129, in load
    self._InitParsedStyleSheetIfNeeded()
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\style_sheet.py", line 136, in _InitParsedStyleSheetIfNeeded
    self.loader, module_dirname, self.contents)
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\style_sheet.py", line 34, in __init__
    self._Load(containing_dirname)
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\style_sheet.py", line 88, in _Load
    self._images = [resolve_url(x) for x in matches]
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\style_sheet.py", line 84, in resolve_url
    image = self.loader.LoadImage(abs_path)
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\resource_loader.py", line 186, in LoadImage
    raise module.DepsException("url('%s') did not exist" % abs_path)
DepsException: While loading:
  z.foo
  z.foo.css
Got: url('c:\x\y\z\foo.jpeg') did not exist

======================================================================
ERROR: testImages (tvcm.style_sheet_unittest.StyleSheetUnittest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\style_sheet_unittest.py", line 29, in testImages
    foo_x = loader.LoadStyleSheet('foo.x')
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\resource_loader.py", line 177, in LoadStyleSheet
    style_sheet.load()
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\style_sheet.py", line 129, in load
    self._InitParsedStyleSheetIfNeeded()
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\style_sheet.py", line 136, in _InitParsedStyleSheetIfNeeded
    self.loader, module_dirname, self.contents)
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\style_sheet.py", line 34, in __init__
    self._Load(containing_dirname)
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\style_sheet.py", line 88, in _Load
    self._images = [resolve_url(x) for x in matches]
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\style_sheet.py", line 84, in resolve_url
    image = self.loader.LoadImage(abs_path)
  File "c:\github\trace-viewer\tracing\third_party\tvcm\tvcm\resource_loader.py", line 186, in LoadImage
    raise module.DepsException("url('%s') did not exist" % abs_path)
DepsException: While loading:
  foo.x.css
Got: url('c:\src\images\bar.jpeg') did not exist

----------------------------------------------------------------------
Ran 87 tests in 11.067s

FAILED (errors=3, skipped=22)

**Comment by natduca** [comment]
I believe there's a relPathIfPossible function laying around somewhere in either tvcm or telemetry that we just need to switch to using from relPath... basically it internally abspaths, then checks if the drive letter has changed. if so, itreturns the abspath , else it returns the relpath

**Comment by anniesullie** [comment]
Thanks! I'll take a look.

**Comment by anniesullie** [comment]
I couldn't find the function in tracing or telemetry. I have a patchset that works, but it's super ugly. Will take a look at implementing @natduca's suggestion Monday.
