### ISSUE TITLE
d8_runner.py needs to import sys

### ISSUE THREAD

**Issue by martijncoenen** [google/trace-viewer#1125]
Traceback (most recent call last):
  File "./d8_runner", line 13, in <module>
    sys.exit(d8_runner.main())
  File "/usr/local/google/home/maco/src/trace-viewer/tracing/build/d8_runner.py", line 233, in main
    js_args=args.js_args, stdout=sys.stdout, stdin=sys.stdin)
NameError: global name 'sys' is not defined

**Comment by nedn** [comment]
*Note that d8_runner now is toplevel/third_party/vinn/bin/vinn
