### ISSUE TITLE
"git checkout -b my_branch" workflow broken

### ISSUE THREAD

**Issue by ChrisCraik** [google/trace-viewer#946]
My standard workflow "git checkout -b my_branch" from a origin/master branch seems to have broken starting with 35c48d0c19f8d2734c2873c4924e08d4fc59450e. I get the following error/dump:

```
Running presubmit upload checks ...
Traceback (most recent call last):
  File "/usr/local/google/depot_tools//git_cl.py", line 3140, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/google/depot_tools//git_cl.py", line 3124, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/usr/local/google/depot_tools/subcommand.py", line 245, in execute
    return command(parser, args[1:])
  File "/usr/local/google/depot_tools//git_cl.py", line 2063, in CMDupload
    change=change)
  File "/usr/local/google/depot_tools//git_cl.py", line 952, in RunHook
    rietveld_obj=self.RpcServer())
  File "/usr/local/google/depot_tools/presubmit_support.py", line 1470, in DoPresubmitChecks
    results += executer.ExecPresubmitScript(presubmit_script, filename)
  File "/usr/local/google/depot_tools/presubmit_support.py", line 1387, in ExecPresubmitScript
    result = eval(function_name + '(*__args)', context)
  File "<string>", line 1, in <module>
  File "<string>", line 20, in CheckChangeOnUpload
  File "<string>", line 13, in CheckChange
  File "/media/ccraik/google2/trace-viewer/hooks/pre_commit.py", line 187, in GetResults
    return RunChecks(input_api)
  File "/media/ccraik/google2/trace-viewer/hooks/pre_commit.py", line 161, in RunChecks
    results += pre_commit_checks.RunChecks(input_api)
  File "/media/ccraik/google2/trace-viewer/hooks/pre_commit_checks.py", line 188, in RunChecks
    results += CheckCopyright(input_api)
  File "/media/ccraik/google2/trace-viewer/hooks/pre_commit_checks.py", line 88, in CheckCopyright
    sources = list(input_api.AffectedFiles(include_deletes=False))
  File "/media/ccraik/google2/trace-viewer/hooks/pre_commit.py", line 121, in AffectedFiles
    filename_statuses = self._GetFilenameStatuses()
  File "/media/ccraik/google2/trace-viewer/hooks/pre_commit.py", line 137, in _GetFilenameStatuses
    'diff', self.diff_base, '--cached', '--name-status'])
  File "/media/ccraik/google2/trace-viewer/hooks/pre_commit.py", line 98, in _git
    raise Exception(res[1])
Exception: fatal: No upstream configured for branch 'test'
```
Reverting that locally works around the issue, and lets me start the upload process.

I'm not blocked - Nat pointed me to "git checkout -t -b my_branch origin/master", but wanted to check if this is intended or not.

cc @petrcermak @primiano @natduca

**Comment by primiano** [comment]
I am  not familiar with the specific change made there, but just git
checkout - b is generally a bad idea (doesn't justify the fact that
presubmit checks are broken in that case though).
in git you really want to always track an upstream branch (unless you are
making just a backup / local testing branch) , which materially translates
into:
git checkout -b branchname -t origin/master

otherwise cl upload gets ambiguous : What is the thing you want to upload?
the diff from the current HEAD down to what?

anyways those presubmit checks should got fixed. not sure why they look at
diff - - cached, will look at the tomorrow emea time with Peter

**Comment by ChrisCraik** [comment]
Alright, thanks. Agreed that it's dangerous/ambiguous - I've been using "git checkout -b" starting from a branch tracking origin/master, but I should probably just be explicit with it.

**Comment by primiano** [comment]
ah and oh, you can always set branch.autosetupmerge and sutosetuprebase in
your git config to avoid having to remember the - t option every time.
see http://stackoverflow.com/a/22147540

anyways, those presumit checks should be fixed regardless.

**Comment by dj2** [comment]
We want to keep checkout -b working. It's ways worked in the past, works for trace-viewer, blink, chromium.  We shouldn't add extra syntax in to break our broken presubmits.

I've never used -t and haven't had any issues yet ....

**Comment by dj2** [comment]
I've reverted 35c48d0 so this is fixed.
