### ISSUE TITLE
Encoding crashes in Python code

### ISSUE THREAD

**Issue by petrcermak** [google/trace-viewer#952]
The following crashes now occur in the Trace Viewer Python code (both locally and on Travis):

```
ERROR: test_smokeTest (trace_viewer.build.generate_about_tracing_contents_unittest.GenerateAboutTracingContentsUnittTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/google/trace-viewer/trace_viewer/build/generate_about_tracing_contents_unittest.py", line 15, in test_smokeTest
    res = generate_about_tracing_contents.main(['--outdir', tmpdir])
  File "/home/travis/build/google/trace-viewer/trace_viewer/build/generate_about_tracing_contents.py", line 58, in main
    minify=not options.no_min)
  File "/home/travis/build/google/trace-viewer/third_party/tvcm/tvcm/generate.py", line 155, in GenerateJSToFile
    minified_js = _MinifyJS(js)
  File "/home/travis/build/google/trace-viewer/third_party/tvcm/tvcm/generate.py", line 79, in _MinifyJS
    res = p.communicate(input=input_js)
  File "/opt/python/2.7.9/lib/python2.7/subprocess.py", line 799, in communicate
    return self._communicate(input)
  File "/opt/python/2.7.9/lib/python2.7/subprocess.py", line 1409, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/opt/python/2.7.9/lib/python2.7/subprocess.py", line 1473, in _communicate_with_poll
    input_offset += os.write(fd, chunk)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xae' in position 871: ordinal not in range(128)
```

```
The command "./vulcanize_trace_viewer --config=chrome" exited with 1.
$ ./vulcanize_trace_viewer --config=full
Traceback (most recent call last):
  File "./vulcanize_trace_viewer", line 12, in <module>
    sys.exit(vulcanize_trace_viewer.Main(sys.argv[1:]))
  File "/home/travis/build/google/trace-viewer/trace_viewer/build/vulcanize_trace_viewer.py", line 57, in Main
    report_deps=options.report_deps)
  File "/home/travis/build/google/trace-viewer/trace_viewer/build/vulcanize_trace_viewer.py", line 89, in WriteTraceViewer
    output_html_head_and_body=output_html_head_and_body)
  File "/home/travis/build/google/trace-viewer/third_party/tvcm/tvcm/generate.py", line 289, in GenerateStandaloneHTMLToFile
    x = GenerateJS(load_sequence, minify=minify, report_sizes=report_sizes)
  File "/home/travis/build/google/trace-viewer/third_party/tvcm/tvcm/generate.py", line 99, in GenerateJS
    report_sizes=report_sizes)
  File "/home/travis/build/google/trace-viewer/third_party/tvcm/tvcm/generate.py", line 155, in GenerateJSToFile
    minified_js = _MinifyJS(js)
  File "/home/travis/build/google/trace-viewer/third_party/tvcm/tvcm/generate.py", line 79, in _MinifyJS
    res = p.communicate(input=input_js)
  File "/opt/python/2.7.9/lib/python2.7/subprocess.py", line 799, in communicate
    return self._communicate(input)
  File "/opt/python/2.7.9/lib/python2.7/subprocess.py", line 1409, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/opt/python/2.7.9/lib/python2.7/subprocess.py", line 1473, in _communicate_with_poll
    input_offset += os.write(fd, chunk)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xae' in position 144: ordinal not in range(128)
```

In both cases, the problem is caused by the **<tt>ascii</tt> codec** being **unable to encode <tt>u'\xae'</tt>** (the registered trademark symbol ®).

The ® symbol was accidentally added to a comment in 7587566 ([here](https://github.com/google/trace-viewer/commit/75875661c84c4116b9a98454c1ab87902bde39c3#diff-a556e844cfff4a5f31560d17b4da9b8eR148)) instead of 'r'.

**Comment by petrcermak** [comment]
This should now be fixed.
